In [1]:
import numpy as np

In [2]:
A = np.array([[5,10],[10,5]])

In [9]:
la,U = np.linalg.eig(A)

In [19]:
U

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [20]:
la.shape

(2,)

In [34]:
U@np.eye(la.shape[0])*la@np.linalg.inv(U)

array([[ 5., 10.],
       [10.,  5.]])

In [23]:
B = np.array([[5,5],[5,5]])

In [30]:
la_b,U_b = np.linalg.eig(B)

In [31]:
la_b

array([1.0000000e+01, 8.8817842e-16])

In [33]:
U_b@la_b@U_b.T

array([ 0., 10.])