In [194]:
import pandas as pd 
import numpy as np
import jieba 
import jieba.analyse

In [41]:
with open ('./chinese_stopwords.txt','r',encoding='utf-8') as file :
    stopwords = [i[:-1] for i in file.readlines()]

In [42]:
stopwords

['，',
 '的',
 '。',
 '、',
 '在',
 '了',
 '是',
 '\u3000',
 '“',
 '”',
 '和',
 '年',
 '月',
 '：',
 '也',
 '）',
 '为',
 '（',
 '有',
 '%',
 '日',
 '将',
 '中',
 '-',
 '到',
 '与',
 '对',
 ':',
 '\xa0',
 '上',
 '都',
 '等',
 '不',
 '他',
 '》',
 '《',
 '就',
 '但',
 '我',
 '而',
 '这',
 '会',
 '并',
 '；',
 '被',
 '后',
 '人',
 '从',
 '还',
 '1',
 '3',
 '6',
 '以',
 '新',
 '说',
 '7',
 '2',
 '要',
 '5',
 '？',
 '更',
 '于',
 '个',
 '10',
 '大',
 '时',
 '4',
 '多',
 '/',
 '让',
 '其',
 ')',
 '(',
 '很',
 '及',
 '下',
 '',
 '能',
 '—',
 '或',
 '该',
 '她',
 '比',
 '8',
 '元',
 '12',
 '已',
 '向',
 '做',
 '来',
 '前',
 '由',
 '好',
 '.',
 '称',
 '给',
 '最',
 '11',
 '·',
 '据',
 '着',
 '又',
 '至',
 '9',
 '20',
 '！',
 '[',
 ']',
 '去',
 '可',
 '把',
 '则',
 '',
 '一',
 '地',
 '高',
 '吗',
 '30',
 '所',
 '分',
 '较',
 '内',
 '第',
 '里',
 '占',
 '过',
 '15',
 '曾',
 '"',
 '再',
 '人民日报',
 '新闻网',
 '它',
 '况',
 '而且',
 '而是',
 '而外',
 '而言',
 '而已',
 '尔后',
 '反过来',
 '反过来说',
 '反之',
 '非但',
 '非徒',
 '否则',
 '嘎',
 '嘎登',
 '该',
 '赶',
 '个',
 '各',
 '各个',
 '各位',
 '各种',
 '各自',
 '给',
 '根据',
 '跟',
 '故',
 '

In [429]:
df = pd.read_csv('./sqlResult.csv',encoding='gb18030')

In [431]:
df.shape

(89611, 7)

In [435]:
# 如果source为空的话在后面的map 获取标签的时候会报错
df = df.dropna(subset=['content','source'])
# 去重，观察发现相邻的数据有很重复的
last = df.loc[3]
drop_index =[]
for i,v in df.iterrows():
    if last['content'] == v["content"] and last['source'] ==v['source']:
        drop_index.append(i)
    else:
        last = v
#因为后面的计算都是基于index的所以这里必须重置index，不然会报错
df.drop(drop_index,inplace=True)
df.reset_index(drop=True,inplace=True)
df.shape

(80908, 7)

In [434]:
df['content'][-10:]

80898    新华社照片，外代，2017年6月7日\n（外代二线）足球——国际友谊赛：德国平丹麦\n6月6...
80899    新华社照片，外代，2017年6月7日\n（外代二线）足球——国际友谊赛：德国平丹麦\n6月6...
80900    新华社照片，北京，2017年6月7日\n电影《血战湘江》举行清华大学巡映活动\n6月6日，电...
80901    新华社照片，北京，2017年6月7日\n电影《血战湘江》举行清华大学巡映活动\n6月6日，清...
80902    新华社照片，北京，2017年6月7日\n电影《血战湘江》举行清华大学巡映活动\n6月6日，电...
80903    新华社照片，多伦多，2017年6月7日\n（体育）（2）冰球——国家女子冰球队海外选秀在多伦...
80904    新华社兰州6月3日电（王衡、徐丹）记者从甘肃省交通运输厅获悉，甘肃近日集中开建高速公路、普通...
80905    \n\n2017年5月29日，在法国巴黎郊外的凡尔赛宫，法国总统马克龙出席新闻发布会。（新华...
80906    \n\n2017年5月25日，在美国马萨诸塞州剑桥市，哈佛大学毕业生在毕业典礼上欢呼。（新华...
80907    　　新华社德国杜塞尔多夫６月６日电题：乒乓女球迷　\n　　新华社记者王子江、张寒\n　　熊老...
Name: content, dtype: object

### 如果用jieba包装好的 TF-IDF的话就要自己转换为一个矩阵，我放弃了

In [19]:
jieba.analyse.set_stop_words('./chinese_stopwords.txt')

In [21]:
df['content'][0]

'此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/体验版内测，稳定版暂不受影响），以确保工程师可以集中全部精力进行系统优化工作。有人猜测这也是将精力主要用到MIUI 9的研发之中。\r\nMIUI 8去年5月发布，距今已有一年有余，也是时候更新换代了。\r\n当然，关于MIUI 9的确切信息，我们还是等待官方消息。\r\n'

In [25]:
jieba.analyse.extract_tags(df['content'][0],topK=30,withWeight=True)

[('MIUI', 0.8150977842886362),
 ('机型', 0.4102491058531818),
 ('精力', 0.35355385647545456),
 ('体验版', 0.3001711470772727),
 ('系统优化', 0.3001711470772727),
 ('稳定版', 0.2716992614295454),
 ('暂不受', 0.2716992614295454),
 ('官方消息', 0.26598756987727273),
 ('内测', 0.2594493409590909),
 ('距今已有', 0.23577993471363634),
 ('发布', 0.23146177423590908),
 ('更新换代', 0.22403696327590908),
 ('小米', 0.20828361826318179),
 ('用到', 0.20189540489000002),
 ('有余', 0.18843649674522728),
 ('确切', 0.17779625928704546),
 ('工程师', 0.17722997857636363),
 ('暂停', 0.1726415647625),
 ('猜测', 0.1643738500809091),
 ('研发', 0.15404115894045456),
 ('更新', 0.15126672967363636),
 ('确保', 0.14988221862022727),
 ('手机', 0.14026867791181818),
 ('等待', 0.13965705640613638),
 ('本周', 0.13263015364159092),
 ('之中', 0.12908492008386363),
 ('去年', 0.12571637589522727),
 ('开发', 0.12561120554204547),
 ('一年', 0.12036832846477273),
 ('信息', 0.11940592483568181)]

### 参考老师的方法用sk_learn中的方法来解决
  - 在jupyter中如果我实例化两个CountVectorizer对象的话第二个对象在调用get_feature会报错 NotFittedError: Vocabulary not fitted or provided


In [317]:
def cut_words(text):
    text = text.strip().replace(' ','').replace('\n','').replace('\r','')
    # 用空格链接是因为countvectorizer 接收的是一个文本，而且是用空格来切分
    return ' '.join(jieba.cut(text))

In [318]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [436]:
courpus = list(map(cut_words,df['content'].values))
countvectorizer = CountVectorizer(encoding='gb18030',min_df=0.015,stop_words=stopwords,analyzer='word')
countvector = countvectorizer.fit_transform(courpus)

In [437]:
countvector.shape

(80908, 936)

In [114]:
countvectorizer.get_feature_names()

['100',
 '13',
 '14',
 '16',
 '17',
 '18',
 '19',
 '200',
 '2014',
 '2015',
 '2016',
 '2017',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '31',
 '40',
 '50',
 '60',
 '70',
 '80',
 'ai',
 'n2017',
 'n3',
 'n4',
 'n5',
 'n6',
 'nba',
 '一个',
 '一些',
 '一份',
 '一位',
 '一名',
 '一场',
 '一天',
 '一定',
 '一家',
 '一带',
 '一年',
 '一批',
 '一条',
 '一次',
 '一步',
 '一直',
 '一种',
 '一系列',
 '一起',
 '一路',
 '一轮',
 '一项',
 '万人',
 '万元',
 '三个',
 '上升',
 '上午',
 '上海',
 '上涨',
 '上述',
 '下午',
 '下降',
 '不仅',
 '不会',
 '不再',
 '不到',
 '不同',
 '不少',
 '不敌',
 '不断',
 '不是',
 '不能',
 '不过',
 '专业',
 '专家',
 '专电',
 '专门',
 '世界',
 '世纪',
 '业务',
 '东部',
 '丝绸之路',
 '两个',
 '两年',
 '严格',
 '严重',
 '个人',
 '中国',
 '中央',
 '中心',
 '中超',
 '丰富',
 '为主',
 '为期',
 '主任',
 '主办',
 '主动',
 '主场',
 '主席',
 '主要',
 '主题',
 '举办',
 '举行',
 '之前',
 '之后',
 '之间',
 '乒乓球',
 '习近平',
 '了解',
 '事业',
 '事件',
 '二线',
 '互动',
 '互联网',
 '亚洲',
 '交易',
 '交流',
 '交通',
 '产业',
 '产品',
 '产生',
 '享受',
 '亮相',
 '人们',
 '人员',
 '人士',
 '人才',
 '人数',
 '人民',
 '人民币',
 '亿元',
 '亿美元',
 '今天',
 '今年',
 '今日',
 '介绍'

In [438]:
tfidf_transformer = TfidfTransformer()
tfidf = tfidf_transformer.fit_transform(countvector)

In [440]:
label = np.array(list(map(lambda s: 1 if '新华' in s else 0 ,df['source'].values)))

### 风格预测，感觉并没有什么用

In [325]:
from sklearn.model_selection import train_test_split

In [177]:
train_x,test_x,train_y,test_y = train_test_split(tfidf.toarray(),label,test_size=0.3)

In [326]:
from sklearn.naive_bayes import MultinomialNB

In [327]:
model = MultinomialNB()
model.fit(train_x,train_y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [328]:
pridict_y = model.predict(train_x)

### KMeans 分类

In [441]:
from sklearn.preprocessing import Normalizer
from sklearn.cluster import KMeans

In [442]:
normalizer = Normalizer()
scaled_array = normalizer.fit_transform(tfidf.toarray())

In [443]:
kmeans = KMeans(n_clusters=5)

In [444]:
k_labels = kmeans.fit_predict(scaled_array)

In [445]:
k_labels[-10:]

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [446]:
k_labels[-20:]

array([1, 0, 0, 2, 2, 2, 1, 2, 1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int32)

In [238]:
type(k_labels)

numpy.ndarray

In [447]:
from sklearn.metrics.pairwise import cosine_similarity

## 找出相识度Top10
### 其实我要做的的就是在同一个类别里面求 cosine_similarty 在排序
    - 我需要排除这个类别中的新华社

In [504]:
def find_similar_text(text_index,top=10):
    """
        找出相似度top排行的新闻
        Arg：
            text_index：int 新闻的id
            top ：int default=10 排行的前几个
        Return：
            index_list ：list 排名前面的新闻在df中的index
            cs ： consine——similarity的降序排序
    """
    class_id = k_labels[text_index]
    # 保存的是index 
    class_id_list = np.array(np.where(k_labels == class_id))[0] 
    #我还要删除这个类别中是新华社的 我自己也属于新华社的
    index_list = np.array([i for i in class_id_list if '新华' not in df['source'][i]])  
    #如果某一类都是新华社的，全部都排除了应该直接返回 []
    if index_list == []:
        return [],[]
    #计算cosine_similarty
    cs = [ cosine_similarity(tfidf[i],tfidf[text_index])[0][0] for i in index_list]
    #拿到前10 index 
    index_top = np.argsort(cs)[::-1][:10]
    return index_list[index_top],[cs[i] for i in index_top]

In [497]:
text_id = 999

In [473]:
def get_index(text_id):
    return df[df['id']==text_id].index[0]

In [505]:
index_top,value_top = find_similar_text(get_index(text_id))

(52549,)
8166


/Users/caoyongjun/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:21: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


In [506]:
index_top

array([2296, 6541, 7736, 3883, 8467, 8313, 1551, 2661, 1585, 7918])

In [507]:
value_top

[0.6860992688372883,
 0.6154376324404998,
 0.6076514388567518,
 0.5862994748794467,
 0.5792828060020455,
 0.573221304970337,
 0.5443765423594822,
 0.5287458362367986,
 0.5264813282487186,
 0.5224226805424779]

In [501]:
[df.loc[i]['content'] for i in index_top]

['作者：刘杉，凤凰财经研究院院长\r\n“一带一路”作为中国首倡的国际议题，其影响力逐渐增大，并引起越来越多国家的重视。\r\n5月14日——15日，“一带一路”国际合作高峰论坛在北京举行，这是“一带一路”框架内层级最高、规模最大的国际会议。一直对中国倡议持怀疑态度的美国日本，分别派出代表团参加此次论坛，这预示着中国或与美日开启新的合作之门，也表明国际社会对“一带一路”建设形成更多共识。\r\n国家主席习近平14日出席“一带一路”国际合作高峰论坛开幕式，并发表题为《携手推进“一带一路”建设》的主旨演讲，提出将“一带一路”建成和平、繁荣、开放、创新、文明之路。\r\n在全球化出现逆流背景下，中国利用主场外交，大力推动“一带一路”建设，其目的既在于打开国际合作空间，也是藉此机会强化全球化主张，提高中国在国际治理中的地位。习近平在此前提出的共商、共建、共享理念基础上，进一步明确“一带一路”的建设愿景，即和平、繁荣、开放、创新、文明之路。\r\n“一带一路”建设倡议，是中国国家主席习近平于2013年秋天，分别在哈萨克斯坦和印度尼西亚提出的，从最初单独构想，发展成完整方案，其背后体现的是中国对国际格局认识的不断深化，也是中国参与国际治理的意识不断增强的过程。据官方报道，“一带一路”建设四年来取得重要进展，全球100多个国家和国际组织积极支持和参与“一带一路”建设，联合国大会、联合国安理会等重要决议也纳入“一带一路”建设内容。\r\n实际上，中国在四年间对其认识也出现了质变过程。\r\n其一，从区域经济合作概念，发展为国际议题。\r\n习近平主席是于2013年9月在哈萨克斯坦纳扎尔巴耶夫大学演讲时提出用创新的合作模式，共同建“丝绸之路经济带”。习近平建议有关国家加强政策沟通，本着求同存异原则，协商制定推进区域合作的规划和措施，在政策和法律上为区域经济融合“开绿灯”。与此同时，加强道路联通、贸易畅通、货币流通和民心相通。\r\n同年10月，习近平在印度尼西亚国会演讲时提出，中国愿同东盟国家加强海上合作，使用好中国政府设立的中国—东盟海上合作基金，发展好海洋合作伙伴关系，共同建设21世纪“海上丝绸之路”。\r\n中国对“一带一路”的最初构想，起步于区域经济合作。而随着国际格局的变化，中国将“一带一路”设想向西延伸，成为亚欧非国家参与，更具开放性的国际倡议。将两个区域性经济合作建议

In [502]:
df.loc[get_index(text_id)]['content']

'新华社西安6月6日电题：中国“西北角”加速融入“一带一路”大格局\\n新华社记者沈虹冰、石志勇、张斌\\n从“中国倡议”到“中国行动”，“一带一路”国际合作高峰论坛之后，西北省份利用丝绸之路区位优势率先行动，在“一带一路”实践中将“中国方案”转变成开放合作机遇。6月3日在古丝路起点城市西安开幕的2017丝绸之路国际博览会吸引了全球42个国家和地区的嘉宾、客商参会。已经举办4年的丝博会正让西北地区迎来更为广阔的对外合作空间，从而加速融入“一带一路”大格局之中。\\n（小标题）抢抓“一带一路”建设机遇\\n6月3日，在2017丝绸之路国际博览会现场，陕西索越户外用品有限公司总经理吕志显得十分激动，他刚刚与尼泊尔商会会长拉杰什·卡齐·施雷斯塔签订了119万元的户外用品订单。在2016年丝博会上，吕志会的产品就曾吸引对方，今年是双方第二次合作。\\n吕志会所在的陕西省白河县位于秦巴山区集中连片特困区，是“土无三寸厚，地无百亩平，山高石头多，出门就爬坡”的国家扶贫开发重点县。如今借着“一带一路”的东风，地处西部的白河县也搭上了对外贸易合作的快车。\\n“去年，我们公司在印度、尼泊尔、伊朗等国家的销售额就超过600万元人民币，今年我们还要扩厂增产，继续提高外贸销量。”吕志会说，“我们县上还打算把土特产也销往‘一带一路’沿线国家！”\\n作为推进“一带一路”合作交流的重要平台，2017丝绸之路国际博览会以“新平台·新机遇·新发展”为主题，内容涉及“一带一路”沿线地区投资和经贸、旅游文化、商标品牌、教育合作、中小企业合作等领域。\\n在本次丝博会上，为寻求在“一带一路”上的合作机会，云南、四川、重庆、甘肃等西部省市和新疆生产建设兵团都组织了大批企业参会，推介自己的优势产业和特色产品。广西壮族自治区则举办了健康产业投资合作推介会，力图推动与“一带一路”沿线国家在“健康丝绸之路”领域的合作。\\n作为东道主的陕西省，则在本次丝博会上积极推介陕西最具发展优势和对外合作潜力的能源化工、现代农业、现代物流等7个产业。“能源化工产业是陕西的传统支柱产业，特别经过近几年的创新发展，已步入高端化、精细化、清洁化的发展阶段。”陕西省商务厅副厅长唐宇刚说，陕西正在积极拓展对外投资合作，愿与相关企业开展这方面的合作。\\n（小标题）加速融入全球价值链\\n过去4年来，随着“一带一路”倡议深入人心，来自